### DISCUSSION TITLE
VASP PBE 6.4 pseudopotentials

### DISCUSSION THREAD

**Discussion by janosh** [materialsproject/pymatgen#3488] [Announcements]
Re-posted here from [@Andrew-S-Rosen's commit comment](https://github.com/materialsproject/pymatgen/commit/f7c92fa76adf9ef89adaf9a7b370146f64a974e6#r133748767) for better visibility and to solicit further discussion.

> @janosh, @esoteric-ephemera: Out of curiosity, are there any planned changes for the PBE .64 set, or is everything going to match the .54 set in terms of the "flavor" of POTCAR chosen? Curious to know what your unofficial recommendations are.

### Summary of current state

@Andrew-S-Rosen short answer: no planned changes for which symbol we use for a given element between the 6.4 and 5.4 potentials for now.

Long answer: I'll post here (with permission) a summary of a private email thread with @michaelwolloch, @sudarshanv01 (VASP developers) and @esoteric-ephemera on the topic.

- PBE 64 potentials are strongly recommended, even just for the lanthanide PSPs which Georg Kresse recreated from scratch after the authors of https://arxiv.org/abs/2305.17274 noticed issues in earlier PSP versions (though the recreation process explicitly did not involve fitting to the AE data in that study)
- @michaelwolloch performed a recheck of 960 systems with vasp.6.4.1, expecting differences in results due to 6 new potentials. Key findings:
   - 15 out of 60 changed EOSs show less than excellent agreement (eps<=0.06) betwen 54 and 64, with 13 improved and 2 slightly worse compared to AE reference.
   - Significant improvements in all Cu systems and specific He and Ba compounds.
   - Slight deterioration in Rn results compared to AE.
   - @MichaelWolloch ran these checks with the potential mapping list of the paper, so mostly GW PSPs. the improved C_h, N_h, F_h, as well as Cs_sv and the non_h Lanthanides were not part of his testing. See YAML below for exact POTCARs used.
      
      <details>
      <summary>POTCAR mapping</summary>

      ```yml
      RECOMMENDED_ACWF: {
        'H': 'H_GW',
        'He': 'He_GW',
        'Li': 'Li_sv_GW',
        'Be': 'Be_sv_GW',
        'B': 'B_GW',
        'C': 'C_GW',
        'N': 'N_GW',
        'O': 'O_h_GW',
        'F': 'F_GW',
        'Ne': 'Ne_GW',
        'Na': 'Na_sv_GW',
        'Mg': 'Mg_sv_GW',
        'Al': 'Al_GW',
        'Si': 'Si_GW',
        'P': 'P_GW',
        'S': 'S_GW',
        'Cl': 'Cl_GW',
        'Ar': 'Ar_GW',
        'K': 'K_sv_GW',
        'Ca': 'Ca_sv_GW',
        'Sc': 'Sc_sv_GW',
        'Ti': 'Ti_sv_GW',
        'V': 'V_sv_GW',
        'Cr': 'Cr_sv_GW',
        'Mn': 'Mn_sv_GW',
        'Fe': 'Fe_sv_GW',
        'Co': 'Co_sv_GW',
        'Ni': 'Ni_sv_GW',
        'Cu': 'Cu_sv_GW',
        'Zn': 'Zn_sv_GW',
        'Ga': 'Ga_d_GW',
        'Ge': 'Ge_d_GW',
        'As': 'As_GW',
        'Se': 'Se_GW',
        'Br': 'Br_GW',
        'Kr': 'Kr_GW',
        'Rb': 'Rb_sv_GW',
        'Sr': 'Sr_sv_GW',
        'Y': 'Y_sv_GW',
        'Zr': 'Zr_sv_GW',
        'Nb': 'Nb_sv_GW',
        'Mo': 'Mo_sv_GW',
        'Tc': 'Tc_sv_GW',
        'Ru': 'Ru_sv_GW',
        'Rh': 'Rh_sv_GW',
        'Pd': 'Pd_sv_GW',
        'Ag': 'Ag_sv_GW',
        'Cd': 'Cd_sv_GW',
        'In': 'In_d_GW',
        'Sn': 'Sn_d_GW',
        'Sb': 'Sb_d_GW',
        'Te': 'Te_GW',
        'I': 'I_GW',
        'Xe': 'Xe_GW',
        'Cs': 'Cs_sv_GW',
        'Ba': 'Ba_sv_GW',
        'La': 'La_GW',
        'Ce': 'Ce_GW',
        'Pr': 'Pr_h',
        'Nd': 'Nd_h',
        'Pm': 'Pm_h',
        'Sm': 'Sm_h',
        'Eu': 'Eu_h',
        'Gd': 'Gd_h',
        'Tb': 'Tb_h',
        'Dy': 'Dy_h',
        'Ho': 'Ho_h',
        'Er': 'Er_h',
        'Tm': 'Tm_h',
        'Yb': 'Yb_h',
        'Lu': 'Lu',
        'Hf': 'Hf_sv_GW',
        'Ta': 'Ta_sv_GW',
        'W': 'W_sv_GW',
        'Re': 'Re_sv_GW',
        'Os': 'Os_sv_GW',
        'Ir': 'Ir_sv_GW',
        'Pt': 'Pt_sv_GW',
        'Au': 'Au_sv_GW',
        'Hg': 'Hg_sv_GW',
        'Tl': 'Tl_d_GW',
        'Pb': 'Pb_d_GW',
        'Bi': 'Bi_d_GW',
        'Po': 'Po_d_GW',
        'At': 'At_d_GW',
        'Rn': 'Rn_d_GW',
        'Fr': 'Fr_sv',
        'Ra': 'Ra_sv',
        'Ac': 'Ac',
        'Th': 'Th',
        'Pa': 'Pa',
        'U': 'U',
        'Np': 'Np',
        'Pu': 'Pu',
        'Am': 'Am',
        'Cm': 'Cm'
      }
      ```
      </details>

**Re new hard Lanthanide PSPs**
- @michaelwolloch noted issues with non-`_h` potentials in older PSP releases which are now resolved
- the new hard (`_h`) potentials for lanthanides should be more (chemically) transferable, because they handle short bond length better. they might also transfer better between functionals which could be relevant for MP given same PSPs used for PBE and r2SCAN but that would require careful testing to make sure.
  - highest required ENMAX by any of the hard rare earth PSPs seems to be 773 eV for `F_h` which isn't that far from the 680 eV `ENCUT` MP already uses for r2SCAN
- New docs on VASP PSPs are underway (covering when to use which ones), aiming to improve clarity/readability
