### ISSUE TITLE
GH workflows check not on fork

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2345]
Would be good to add a check to all GH workflows so that they don't run on forks.

```yaml
jobs:
  test:
    if: github.repository_owner == 'materialsproject'
# ...
```

Would save compute and it's annoying to keep getting emails about failed runs on my fork when submitting PRs:

<img width="866" alt="Screen Shot 2022-01-12 at 18 35 01" src="https://user-images.githubusercontent.com/30958850/149201290-17cd935b-6b8a-4f83-a2fe-5f9167bbee01.png">
