### ISSUE TITLE
Variables in `.pmgrc.yaml` file are no longer acessible since new update to  pymatgen==2022.2.1

### ISSUE THREAD

**Issue by naik-aakash** [materialsproject/pymatgen#2421]
**The bug**
Since the latest update the variables defined in `.pmgrc.yaml` file are no longer acessible after first usage of MPRester. 
Consider the vairables defined for eg in the `~/.pmgrc.yaml` file are as follows : 

```
PMG_DEFAULT_FUNCTIONAL: PBE_54
PMG_VASP_PSP_DIR: /pathtopotcars/POTCAR
PMG_MAPI_KEY: yourkeyfrommp
```

**To Reproduce**
1. IMPORT the MPRester module in Jupyternotebook/Any other python IDE
`from pymatgen.ext.matproj import MPRester`
2. Get a structure from the Materials Project after initializing MPRester
```
m = MPRester()
struct = m.get_structure_by_material_id('mp-xxxx')
```
3. Now restart the Jupyter Notebook kernel
4. Run first two code blocks again
5. You see following error
`MPRestError: REST query returned with error status code 403. Content: b'{"valid_response": false, "error": "API_KEY is not supplied.", "version": {"db": "2020_09_08", "pymatgen": "2022.0.8", "rest": "2.0"}, "created_at": "2022-02-07T02:43:53.161480"}'`

**Expected behavior**
This normally should not happen because, once the variables are defined it were accessible in earlier versions of pymatgen. And currently to use pymatgen I need to always recreate the `~/.pmgrc.yaml` file

**Screenshots**
![Issue](https://user-images.githubusercontent.com/91958822/152774808-2d4d48c1-a934-4595-a096-ce06adc11279.png)

**Comment by JaGeo** [comment]
I just want to add that I have the same problem as @naik-aakash. The .pmgrc.yaml gets overwritten while connecting to the Materials Project database.

**Comment by janosh** [comment]
I had the same problem 2 weeks ago but I thought it was already fixed... @shyuep [said so](https://github.com/materialsproject/pymatgen/issues/2377#issuecomment-1021268224) and I haven't encountered the issue since. So maybe it's a different one given your using latest version. Can you post the contents of your `.pmgrc.yaml` after the error occurs? Is it full of `ruamel.yaml` garbage?

**Comment by naik-aakash** [comment]
@janosh : here is the small snipet as requerted of `.pmgrc.yaml` after the error occurs.
```
!!python/object/apply:ruamel.yaml.comments.CommentedMap
dictitems:
  MAPI_DB_VERSION:
    LAST_ACCESSED: '2020_09_08'
    LOG: {'2020_09_08': 1}
  dictitems: !!python/object/apply:ruamel.yaml.comments.CommentedMap
    dictitems:
      MAPI_DB_VERSION: !!python/object/apply:ruamel.yaml.comments.CommentedMap
        dictitems:
          LAST_ACCESSED: '2020_09_08'
          LOG: !!python/object/apply:ruamel.yaml.comments.CommentedMap
            dictitems: {'2020_09_08': 1}
            state:
              _yaml_format: !!python/object/new:ruamel.yaml.comments.Format
                state: !!python/tuple
                - null
                - {_flow_style: true}
              _yaml_line_col: !!python/object:ruamel.yaml.comments.LineCol
                col: 9
                data:
                  '2020_09_08': [4, 10, 4, 24]
                line: 4
        state:
          _yaml_format: !!python/object/new:ruamel.yaml.comments.Format
            state: !!python/tuple
            - null
            - {_flow_style: false}
          _yaml_line_col: !!python/object:ruamel.yaml.comments.LineCol
            col: 4
            data:
              LAST_ACCESSED: [3, 4, 3, 19]
              LOG: [4, 4, 4, 9]
            line: 3
      PMG_DEFAULT_FUNCTIONAL: PBE_54
      PMG_MAPI_KEY: C09FgeMwsIQtaqWj
      PMG_VASP_PSP_DIR: /home/htc/anaik/POTCAR
    state:
      _yaml_format: !!python/object/new:ruamel.yaml.comments.Format
        state: !!python/tuple
        - null
        - {_flow_style: false}
      _yaml_line_col: !!python/object:ruamel.yaml.comments.LineCol
        col: 2
        data:
          MAPI_DB_VERSION: [2, 2, 3, 4]
          PMG_DEFAULT_FUNCTIONAL: [5, 2, 5, 26]
          PMG_MAPI_KEY: [6, 2, 6, 16]
          PMG_VASP_PSP_DIR: [7, 2, 7, 20]
        line: 2
  state: !!python/object/apply:ruamel.yaml.comments.CommentedMap
    dictitems:
      _yaml_format: !!python/object/apply:ruamel.yaml.comments.CommentedMap
        dictitems:
          state: !!python/object/new:ruamel.yaml.comments.CommentedSeq
            listitems:
            - null
            - !!python/object/apply:ruamel.yaml.comments.CommentedMap
              dictitems: {_flow_style: false}
              state:
                _yaml_format: !!python/object/new:ruamel.yaml.comments.Format
                  state: !!python/tuple
                  - null
                  - {_flow_style: true}
                _yaml_line_col: !!python/object:ruamel.yaml.comments.LineCol
                  col: 6
                  data:
                    _flow_style: [12, 7, 12, 20]
                  line: 12
            state:
              _yaml_format: !!python/object/new:ruamel.yaml.comments.Format
                state: !!python/tuple
                - null
                - {_flow_style: false}
              _yaml_line_col: !!python/object:ruamel.yaml.comments.LineCol {col: 11,
                data: null, line: 10}
              _yaml_tag: !!python/object/new:ruamel.yaml.comments.Tag
                state: !!python/tuple
                - null
                - {value: '!!python/tuple'}
```
