### ISSUE TITLE
Corruption of `.pmgrc.yaml` still happening

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2506]
Pinging @shyuep as I think this was supposed to be fixed in https://github.com/materialsproject/pymatgen/issues/2421.

Using `MPRester` still corrupts `.pmgrc.yaml`:

```yaml
dictitems:
  MAPI_DB_VERSION:
    LAST_ACCESSED: '2020_09_08'
    LOG: {'2020_09_08': 1}
  PMG_DEFAULT_FUNCTIONAL: PBE_54
  PMG_MAPI_KEY: **********************
  PMG_VASP_PSP_DIR: /Users/janosh/dev/vasp/pseudo-potentials
state:
  _yaml_format: !!python/object/new:ruamel.yaml.comments.Format
    state: !!python/tuple
    - 
    - {_flow_style: false}
  _yaml_line_col: !!python/object:ruamel.yaml.comments.LineCol
    col: 0
    data:
      PMG_DEFAULT_FUNCTIONAL: [0, 0, 0, 24]
      PMG_MAPI_KEY: [1, 0, 1, 14]
      PMG_VASP_PSP_DIR: [2, 0, 2, 18]
    line: 0
MAPI_DB_VERSION:
  LOG:
    '2020_09_08': 2
  LAST_ACCESSED: '2020_09_08'
```

leading on subsequent `MPREster` calls to

```py
pymatgen.ext.matproj.MPRestError: REST query returned with error status code 403
```

Is this due to an outdated `ruamel.yaml` on my machine?

```
pip list | grep ruamel  
ruamel.yaml                     0.17.20
ruamel.yaml.clib                0.2.6
```

If so, should update the min version in `setup.py`:

```py
"ruamel.yaml>=0.15.6"
```
