### ISSUE TITLE
Use `astral-sh/setup-uv` in CI

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#4044]
`uv` now has 1st-party GitHub Action support with built-in caching which could speedup our `test.yml` workflow. not sure if it clashes with our `mamba` setup

https://github.com/materialsproject/pymatgen/blob/1404220105d4dc1e421ac603b1cb83daf6b085c5/.github/workflows/test.yml#L64-L72

but if not, would be good to adopt this. should only require adding a new step:

```yml
      - name: Set up uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
```
